version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/mydatabase
    volumes:
      - app-data:/app
    container_name: pini-flask-app
    image: pini-flask-image

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: pini-postgres-container
    image: pini-postgres-image

volumes:
  app-data:
  db-data:
